local map = vim.keymap.set

map("x", "<leader>p", '"_dP')
map("v", "J", ":m '>+1<CR>gv=gv")
map("v", "K", ":m '<-2<CR>gv=gv")
map("v", ">", ">gv")
map("v", "<", "<gv")

map("n", "<leader>h", function()
    vim.lsp.buf.hover()
end)
map("n", "<leader>d", function()
    vim.diagnostic.open_float(nil, { focus = false })
end)
map("n", "<leader>ca", require("actions-preview").code_actions)
map("n", "gd", vim.lsp.buf.definition)
map("n", "gD", vim.lsp.buf.declaration)
map("n", "gi", vim.lsp.buf.implementation)
map("n", "gr", function()
    require("telescope.builtin").lsp_references()
end)

map("n", "<leader>o", "<CMD>Oil<CR>")
map("n", "<leader>y", "<CMD>Yazi<CR>")

map("n", "<leader>ff", require("telescope.builtin").find_files)
map("n", "<leader>fw", require("telescope.builtin").live_grep)
map("n", "<leader>fr", require("telescope.builtin").oldfiles)
map("n", "<leader>fb", require("telescope.builtin").buffers)
map("n", "<leader>fh", require("telescope.builtin").help_tags)
map("n", "<leader>tw", "<CMD>TelescopeThemePicker<CR>")

map("n", "L", "<CMD>tabn<CR>")
map("n", "H", "<CMD>tabp<CR>")
map("n", "<leader>1", "1gt")
map("n", "<leader>2", "2gt")
map("n", "<leader>3", "3gt")
map("n", "<leader>4", "4gt")
map("n", "<leader>n", "<CMD>tabnew<CR>")
map("n", "<leader>D", "<CMD>tab split<CR>")

map("n", "<leader>gg", "<CMD>Neogit<CR>")
map("n", "]g", function()
    require("gitsigns").next_hunk()
end)
map("n", "[g", function()
    require("gitsigns").prev_hunk()
end)

map("n", "<leader>cf", function()
    vim.cmd("write")
    local file = vim.fn.shellescape(vim.fn.expand("%:p"))
    vim.fn.system("clang-format -i " .. file)
    vim.cmd("checktime")
end)

vim.keymap.del("n", "<C-l>")
